language: node_js

sudo: enabled

os: osx

install:
  - npm install

script:
 - npm run build:spec
 - ./node_modules/.bin/istanbul cover ./node_modules/.bin/jasmine
 - npm run coverage

after_success:
 - npm run codecov
 - npm run build

git:
  depth: 5
  submodules: false