language: node_js

sudo: enabled

os: osx

install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul

script:
 - npm run build:spec
 - istanbul cover ./node_modules/.bin/jasmine
 - ./node_modules/.bin/codecov
 - npm run build

after_success:
 - codecov

git:
  depth: 5
  submodules: false