language: node_js

sudo: enabled

os: osx

install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul

script:
 - npm run build:spec
 - istanbul cover node_modules\jasmine\bin\jasmine.js --reporter lcovonly -- -R spec
 - npm run build

after_success:
 - codecov

git:
  depth: 5
  submodules: false