language: node_js

sudo: enabled

os: osx

install:
  - npm install

script:
 - npm run build:spec
 - ./node_modules/.bin/istanbul cover ./node_modules/.bin/jasmine

after_success:
 - npm run build
 - npm run coverage
 - npm run codecov

git:
  depth: 5
  submodules: false