language: node_js

sudo: enabled

os: osx

install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul

script:
 - npm run build:spec
 - istanbul cover ./node_modules/.bin/jasmine

after_success:
 - npm run build
 - ./node_modules/.bin/codecov

git:
  depth: 5
  submodules: false